include: 
  - package:flutter_lints/flutter.yaml
  #- package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - lib/**.mocks.dart
    - lib/**.g.dart
    - lib/**.g.dart
    
  plugins:
    - custom_lint

  errors:
    omit_local_variable_types: info

linter:
  rules:
  - avoid_dynamic_calls: false  
  - public_member_api_docs: false