include: 
  - package:flutter_lints/flutter.yaml
  #- package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    omit_local_variable_types: info
    argument_type_not_assignable: info
    public_member_api_docs: ignore

linter:
  rules:
  - avoid_dynamic_calls: false  
  - public_member_api_docs: false