name: flutter_tech_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.8.0"
  flutter: "^3.35.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.7.1
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  riverpod_annotation: ^3.0.0-dev.17
  sembast: ^3.8.5+1
  dio: ^5.9.0
  mockito: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0
  very_good_analysis: ^9.0.0
  custom_lint: ^0.8.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true